### ISSUE TITLE
Error thrown when trying to select 2 or more fields with 'likeLower'

### ISSUE THREAD

**Issue by drwatsno** [Vincit/objection-find#12]
Objection 0.8.9
Objection-find 0.5.0

When trying to use filter `name|surname:likeLower` got error:

> Unhandled rejection TypeError: Cannot read property 'apply' of undefined
    at PropertyRef.buildFilter (/home/watson/WebstormProjects/pfa-meetups/node_modules/objection-find/lib/PropertyRef.js:148:25)
    at /home/watson/WebstormProjects/pfa-meetups/node_modules/objection-find/lib/FindQueryBuilder.js:447:13
    at /home/watson/WebstormProjects/pfa-meetups/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/watson/WebstormProjects/pfa-meetups/node_modules/lodash/lodash.js:3001:24)
    at /home/watson/WebstormProjects/pfa-meetups/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/home/watson/WebstormProjects/pfa-meetups/node_modules/lodash/lodash.js:9359:14)
    at QueryBuilderBase.<anonymous> (/home/watson/WebstormProjects/pfa-meetups/node_modules/objection-find/lib/FindQueryBuilder.js:446:9)
    at convertQueryBuilderFunction (/home/watson/WebstormProjects/pfa-meetups/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:144:8)
    at Builder.convertedKnexArgumentFunction (/home/watson/WebstormProjects/pfa-meetups/node_modules/objection/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js:131:7)
    at Formatter.compileCallback (/home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/formatter.js:161:14)
    at Formatter.rawOrFn (/home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/formatter.js:104:36)
    at QueryCompiler_PG.whereWrapped (/home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/query/compiler.js:531:30)
    at QueryCompiler_PG.where (/home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/query/compiler.js:314:32)
    at /home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/query/compiler.js:147:30
    at Array.map (<anonymous>)
    at QueryCompiler_PG.select (/home/watson/WebstormProjects/pfa-meetups/node_modules/knex/lib/query/compiler.js:146:33)

getMany method code:

```
async getMany(criteria: SpeakerGetManyCriteria): Promise<{items: Speaker[], total: number}> {
    const { filters: criteriaFilters = {} } = criteria;
    const getFilters = (filters: Object) => {
      const { query, isDeleted } = filters;
      const resultFilters = criteriaFilters;

      if (isString(query)) {
        resultFilters['name|surname:likeLower'] = `%${query}%`;
      }

      if (isDeleted) {
        resultFilters['deletedAt:notNull'] = true;
      }

      return omitBy(flatten(resultFilters), (value: any, key: string) => ['query', 'isDeleted'].includes(key) || value === '');
    };

    return SpeakerModel.getMany({
      ...criteria,
      filters: {
        ...getFilters(criteriaFilters),
      },
    });
  },
```

name|surname:like works well

**Comment by drwatsno** [comment]
looks like problem in wrong method name 'orWhereraw'. Please look at:
https://github.com/Vincit/objection-find/pull/13
