### ISSUE TITLE
Filters don't work when using columnNameMappers

### ISSUE THREAD

**Issue by jejrthompson** [Vincit/objection-find#35]
I have the following mapper:
```
static columnNameMappers = {
    parse(obj) {
      // database --> code
      return {
        id: obj.MktTypeID,
        desc: obj.MktTypeDesc,
        entryDesc: obj.MktTypeEntryDesc,
        active: obj.Active
      };
    },

    format(obj) {
      // code --> database
      return {
        MktTypeID: obj.id,
        MktTypeDesc: obj.desc,
        MktTypeEntryDesc: obj.entryDesc,
        Active: obj.active
      };
    }
  };
```

When I do a query as such: /api/v1/LinkMktType?desc=Other, I get the error:
```
Error: PropertyRef: unknown property desc
    at Object.throwError (c:\git\DCST\api\node_modules\objection-find\lib\utils.js:3:19)
    at PropertyRef._parse (c:\git\DCST\api\node_modules\objection-find\lib\PropertyRef.js:95:13)
    at new PropertyRef (c:\git\DCST\api\node_modules\objection-find\lib\PropertyRef.js:68:10)
    at FindQueryBuilder._parsePropertyRef (c:\git\DCST\api\node_modules\objection-find\lib\FindQueryBuilder.js:498:37)
    at _.reduce (c:\git\DCST\api\node_modules\objection-find\lib\FindQueryBuilder.js:489:28)
    at arrayReduce (c:\git\DCST\api\node_modules\lodash\lodash.js:704:21)
    at Function.reduce (c:\git\DCST\api\node_modules\lodash\lodash.js:9698:14)
    at FindQueryBuilder._parsePropertyRefs (c:\git\DCST\api\node_modules\objection-find\lib\FindQueryBuilder.js:486:14)
    at QueryParameter._parseFilter (c:\git\DCST\api\node_modules\objection-find\lib\QueryParameter.js:89:33)
    at QueryParameter._parse (c:\git\DCST\api\node_modules\objection-find\lib\QueryParameter.js:58:12)
    at new QueryParameter (c:\git\DCST\api\node_modules\objection-find\lib\QueryParameter.js:51:10)
    at _.each (c:\git\DCST\api\node_modules\objection-find\lib\FindQueryBuilder.js:352:21)
    at c:\git\DCST\api\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (c:\git\DCST\api\node_modules\lodash\lodash.js:3001:24)
    at c:\git\DCST\api\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (c:\git\DCST\api\node_modules\lodash\lodash.js:9359:14)
```

I'm using 1.0.0-rc.5.

**Comment by kapouer** [comment]
Hi,
this project needs contributions, so just opening an issue won't fix it.
PR is welcome here !

**Comment by jejrthompson** [comment]
I'm digging through the code now 😄 

Issue seems to be in `modelColPropMap.js` in function `propertyNameToColumnName`

**Comment by kapouer** [comment]
hmmmm why ?

**Comment by igor-savin-ht** [comment]
@jejrthompson Have you managed to resolve the issue without changing the code? If so, would be great if you could describe your solution for whoever stumbles upon this issue in the future.

**Comment by jejrthompson** [comment]
This is related to Objection.js and not objection-find. I posted over there and can update this thread if a solution is found.
