### ISSUE TITLE
Feature request: Throw BadRequest when query parameter contains invalid data

### ISSUE THREAD

**Issue by afm-sayem** [Vincit/objection-find#5]
```
Unhandled rejection error: invalid input syntax for integer: "aou"
    at Connection.parseE (/home/kishan/projects/api-server-seed/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/kishan/projects/api-server-seed/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/kishan/projects/api-server-seed/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
From previous event:
    at Client._query (/home/kishan/projects/api-server-seed/node_modules/knex/lib/dialects/postgres/index.js:179:12)
    at Client.query (/home/kishan/projects/api-server-seed/node_modules/knex/lib/client.js:187:24)
    at Runner.<anonymous> (/home/kishan/projects/api-server-seed/node_modules/knex/lib/runner.js:129:36)
From previous event:
    at /home/kishan/projects/api-server-seed/node_modules/knex/lib/runner.js:55:21
From previous event:
    at Runner.run (/home/kishan/projects/api-server-seed/node_modules/knex/lib/runner.js:41:33)
    at QueryBuilder.Target.then (/home/kishan/projects/api-server-seed/node_modules/knex/lib/interface.js:32:43)
    at QueryBuilder.resultSize (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:611:23)
    at QueryBuilder.<anonymous> (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:642:34)
    at RunBeforeOperation.onBefore (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/operations/RunBeforeOperation.js:44:22)
    at /home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1279:19
    at /home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1324:14
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at /home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1323:23
    at arrayEach (/home/kishan/projects/api-server-seed/node_modules/lodash/lodash.js:451:11)
    at Function.forEach (/home/kishan/projects/api-server-seed/node_modules/lodash/lodash.js:8634:14)
    at promiseChain (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1318:20)
    at chainBeforeOperations (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1278:10)
    at QueryBuilder.execute (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:704:15)
    at QueryBuilder.then (/home/kishan/projects/api-server-seed/node_modules/objection/lib/queryBuilder/QueryBuilder.js:527:24)
    at index (movie.controller.js:40:6)
    at Layer.handle [as handle_request] (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/route.js:131:13)
    at processQuery (utilities.js:64:3)
    at Layer.handle [as handle_request] (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/layer.js:95:5)
    at /home/kishan/projects/api-server-seed/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/index.js:330:12)
    at next (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/kishan/projects/api-server-seed/node_modules/express/lib/router/index.js:176:3)
```

When sending an arbitrary string for an integer field for a find query, `objection-find` constructs the query anyway which results in unhandled exception in server.

Since a models' JSON schema is available to the library, a validation should be run before constructing the query and throw a BadRequest error if it fails the check.

**Comment by kapouer** [comment]
Hi,
we will welcome and process quickly any pull request, along with a test.
